server:
  port: ${gateway-service.port}

spring:
  # 基于WebFlux应用
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  profiles:
    active: dev


  #  数据源配置可以移至 Nacos 配置中心：common-service-dev.yml
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/nacos?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
#    username: root
#    password: 123456

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - info
          - gateway