spring:
  application:
    name: product-service
  cloud:
    sentinel:
      transport:
        port: ${sentinel.transport.port.product-service}
        dashboard: ${sentinel.transport.dashboard}
server:
  port: ${product-service.port}