spring:
  application:
    name: user-service
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: ${nacos.server-address}
        group: ${nacos.group}
        file-extension: ${nacos.file-extension}